### ISSUE TITLE
怎么安装这个插件啊

### ISSUE THREAD

**Issue by LexsMax** [nyaoouo/FFxivPythonTrigger2#12]
RT，python都是刚刚下载的，完全对这方面不会，实在是不知道怎么操作了....

**Comment by nyaoouo** [comment]
https://www.bilibili.com/video/BV1wD4y1o7AS
如果官网的教程未能够看懂的话可以搜索一下网上视频教程呢

**Comment by LexsMax** [comment]
这边现在是装完了，然后在实际使用的时候，注入完毕，在游戏里加载完了插件但是不起作用:(
