### ISSUE TITLE
国际服不支持吗？

### ISSUE THREAD

**Issue by toa-heavyindustries** [nyaoouo/FFxivPythonTrigger2#17]
[log_1626696507.txt](https://github.com/nyaoouo/FFxivPythonTrigger2/files/6841790/log_1626696507.txt)
提示
[ERROR] [2021-07-19 20:08:29.044|AddressManager]                searching address of [player] is failed
[ERROR] [2021-07-19 20:08:29.045|Main]          error occurred during import module:" XivMemory"

**Comment by nyaoouo** [comment]
temporarily, yes
for supporting of international server, some adaptation is needed and i welcome anyone to assist with related work
