### ISSUE TITLE
没有出现防倒卖弹窗，输入donate也不显示token。谢谢谢谢！

### ISSUE THREAD

**Issue by shenzuntian** [nyaoouo/FFxivPythonTrigger2#21]
您好，遇到了一个问题，在前面所有步骤都没错的情况下，挂了梯子进行注入也没有出现防倒卖弹窗，输入/e @wp donate也没有,log如下
[log_1636894591.txt](https://github.com/nyaoouo/FFxivPythonTrigger2/files/7533847/log_1636894591.txt)

**Comment by nyaoouo** [comment]
该插件并非本库进行维护
