### ISSUE TITLE
高难搓不动了

### ISSUE THREAD

**Issue by Hua-Xun** [nyaoouo/FFxivPythonTrigger2#3]
![image](https://user-images.githubusercontent.com/73590107/116782227-6f20ed80-aaba-11eb-9cac-49e93e2317c5.png)
![image](https://user-images.githubusercontent.com/73590107/116782246-8c55bc00-aaba-11eb-946c-b6059fe5dfda.png)
就，搓到崇敬就不动了，也没有什么后续log

**Comment by Hua-Xun** [comment]
顺便还想问问xivcombat怎么用（

**Comment by Hua-Xun** [comment]
![image](https://user-images.githubusercontent.com/73590107/116782533-40a41200-aabc-11eb-93af-a4f05198c02a.png)
不动了...

**Comment by nyaoouo** [comment]
1.当时三围
2.使用什么版本

**Comment by Hua-Xun** [comment]
![image](https://user-images.githubusercontent.com/73590107/116782592-a4c6d600-aabc-11eb-8a01-fcac316405f7.png)
没吃辣蟹做实验
版本是
![image](https://user-images.githubusercontent.com/73590107/116782596-b14b2e80-aabc-11eb-8546-d87f6d05cf05.png)

**Comment by Hua-Xun** [comment]
![image](https://user-images.githubusercontent.com/73590107/116782677-23237800-aabd-11eb-8668-f2490210e086.png)
崇敬之后我自己按了一下高速，它又会搓几下又不动了

**Comment by Hua-Xun** [comment]
log没有报错什么的

**Comment by nyaoouo** [comment]
请更新到最新版本，旧版本将会停止技术支援（
