### ISSUE TITLE
手动填写配方功能

### ISSUE THREAD

**Issue by ykoneee** [nyaoouo/FFxivPythonTrigger2#7]
大佬，之前在用FFxivPythonCraft做自写solver的效率模拟器，但是发现老代码bug比较多，而富婆糖里的recipe 和player又不方便像FFxivPythonCraft手动填写数值，大佬有空更新一个手动填写数值方便离线模拟的功能吗

**Comment by nyaoouo** [comment]
目前来说当前版本不少数值系数依靠直接解包获取，所以独立离线会有一定难度（麻烦）
过几天有空的话我应该可以独立的一个版本出来（咕咕咕咕）

短时间内实在是有需要的话，你可以自己构造
plugins.XivCraft.simulator.Models.Recipe 的class属性
以及
plugins.XivCraft.simulator.Craft.craft_lv_dif_sheet函数（具体参考源码）
修改一下代码就可以离线跑起来了
